---
- hosts: database
  tasks:
  - name: create /mnt/mysql_backups
    file:
      path: /mnt/mysql_backups
      state: directory

  - name: create database_lists.txt file
    copy:
      content: dev,test,qa,prod
      dest: /mnt/mysql_backups/database_lists.txt

  - name: create archive of file
    archive:
      path: /mnt/mysql_backups/database_lists.txt
      dest: /mnt/mysql_backups/archive.gz
