---
- hosts: all
  tasks:
  - name: set swappiness if conditons are met
    sysctl:
      name: vm.swappiness
      value: 10
      state: present
    when: ansible_memtotal_mb > 2048

  - name: print error message if conditons are not met
    debug:
      msg: "Server memory less than 2048"
    when: ansible_memtotal_mb < 2048
