---
- hosts: all
  vars_files:
    - vars/secret.yml
    - vars/user_list.yml
  tasks:
  - name: create users
    user:
      name: "{{ item.username }}"
      uid: "{{ item.uid }}"
      state: present
      password: "{{ user_password | password_hash('sha512') }}"
      shell: /bin/bash
      groups: wheel
    loop: "{{ users }}"
    when:
      - "'webservers' in group_names"
      - ( item.uid | string)[0] == '1'
  
  - name: create users
    user:
      name: "{{ item.username }}"
      uid: "{{ item.uid }}"
      state: present
      password: "{{ user_password | password_hash('sha512') }}"
      shell: /bin/bash
      groups: wheel
    loop: "{{ users }}"
    when:
      - "'database' in group_names"
      - ( item.uid | string)[0] == '2'

  - name: Set authorized key taken from file
    authorized_key:
      user: "{{ item.username }}"
      state: present
      key: "{{ lookup('file', '/home/ansible/.ssh/id_ed25519.pub') }}"
    loop: "{{ users }}"
    when:
      - "'webservers' in group_names"
      - ( item.uid | string)[0] == '1'

  - name: Set authorized key taken from file
    authorized_key:
      user: "{{ item.username }}"
      state: present
      key: "{{ lookup('file', '/home/ansible/.ssh/id_ed25519.pub') }}"
    loop: "{{ users }}"
    when:
      - "'database' in group_names"
      - ( item.uid | string)[0] == '2'
